

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Header */}
        <header className="site-header">
          <div className="container">
            <h1>My Website</h1>
            <nav>
              <a href="/">Home</a>
              <a href="/about">About</a>
              <a href="/contact">Contact</a>
            </nav>
          </div>
        </header>

        {/* Main Content */}
        <main className="site-main">{children}</main>

        {/* Footer */}
        <footer className="site-footer">
          <p>&copy; {new Date().getFullYear()} My Website. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}

